name: Create Release Pull Request

run-name: Create release PR for v${{ github.event.inputs.version }}

on:
  push:
    branches:
      - dev

jobs:
  create-release-pr:
    name: Create release PR

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Bump version and push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b release/$NEW_VERSION
          npx lerna version ${{ github.event.inputs.release-type }}" --yes
          git add **/package.json package-lock.json lerna.json
          git commit -m "Release extension version $NEW_VERSION"
          git push --set-upstream origin release/$NEW_VERSION
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
      - name: Create PR
        run: |
          gh pr create \
            --title "Release version ${{ env.new_version }}" \
            --body "Release version ${{ env.new_version }}" \
            --base main \
            --head release/${{ env.new_version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
